<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIIjm4M2\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIIjm4M2/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIIjm4M2.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIIjm4M2\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIIjm4M2\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'IIjm4M2',
    'container.build_id' => '977c683e',
    'container.build_time' => 1575995317,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIIjm4M2');
