<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEY0HvdO\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEY0HvdO/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEY0HvdO.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEY0HvdO\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerEY0HvdO\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'EY0HvdO',
    'container.build_id' => 'ea5625df',
    'container.build_time' => 1576108121,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEY0HvdO');
